# Variaveis de Ambiente para grupo zabbix ansible
ansible_python_interpreter: auto
ansible_ssh_port: 22
ansible_become : True
ansible_become_user: root
ansible_ssh_user: root
ansible_ssh_pass: 123

# Consulta a versão que busca Instalar em : https://repo.zabbix.com/zabbix/
zbx_version: 5.5
zbx_agent_version: 5.5
version_grafana: 8.3.3
#-----------------------------------------------------------------------------------------------------#

# Variaveis de login API Zabbix 
username: 'Admin'
password: 'zabbix'

# Declarar as variavies do arquivo de hosts
zbx_proxy: 192.168.3.130
allonezbx: 192.168.3.111

#--------------------------- Adção de templates -----------------------------------------------------#
# Macro Padronizada adição de Templates no Agentes 
zabbix_link_templates:
  - Linux by Zabbix agent active
  - ICMP Ping


# VARIAVEL CRIAÇÃDO DO USUARIO ZABBIX LOCALHOST
db_user_zabbix: 'zabbix'
db_user_zabbix_pass: 'zabbix'

# SENHA DO USER LOCAL ROOT
root_pass: 'zabbix'

# VARIAVEL DE TimeZone.
timezone: America/Sao_Paulo

database_remove:
  - test
  - sys
  - perfomance_schema 

# VARIAVEL CRIAÇÃO DO BANCO DE DADOS
db_name: 'zabbix'

# VARIAVEIS DE CRIAÇÃO DE USUARIO ZABBIXMONITDB
db_user_monit_db: 'zabbixmonitdb'
db_user_pass_db: 'zabbixmonitdb'

#------------------------------------------------------------------------------------------------------#
# Variaveis de monitoring db zabbix
# Ajustar conforme sua versão de banco de dados Acessando e verificando versão com comando select version ();
# https://downloads.mysql.com/archives/c-odbc/

version_connector_odbc: 8.0.26
FRONT_DSN: zabbix

#Observação Neste caso do Monitoramento no host banco dados a partir do proxy, podera seguir conforme
# Sua Necessidade e alterando assim, podendo clonar host e adcionar template MYSQL by Zabbix agent2
# Variveis do host User password criado em deploy.zabbix.yml , verificar usuario abaixo adcionado.
# nosso Caso de Exemplo- ZABBIXMONITDB - Informações o usuario remote acima.

# Acionar variaveis aos hosts.

  # {$MYSQL.DSN} - tcp://192.168.3.120:3306
  # {$MYSQL.PASSWORD} -  zabbixmonitdb
  # {$MYSQL.USER} - zabbixmonitdb
