# Variaveis de Ambiente para grupo zabbix ansible
ansible_python_interpreter: auto
ansible_ssh_port: 22
ansible_become : True
ansible_become_user: root
ansible_ssh_user: root
ansible_ssh_pass: 123

# Consulta a versão que busca Instalar em : https://repo.zabbix.com/zabbix/
zbx_version: 5.5
zbx_agent_version: 5.5
version_grafana: 8.3.3

# SCRIPTS PARA MONTAR TABELAS DO BANCO DE DADOS FORAM ALTERADOS DE CREATE.SQL.GZ PARA SERVER.SQL.GZ
#---------------------- Banco de Dados ---------------------------------------------------------------#
# OBS: HABILITAR OU DESABILITAR CONFORME A VERSÃO DO ZABBIX SERVER PARA PARTICIONAMENTO.
# Habilitar abaixo para instalação do Zabbix Versao 6.
url_schema: zcat /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz | mysql -h "{{ zbx_db }}" -u "{{ db_user_server }}"  "{{ db_name }}"

# habilitar para Versão 5.4 Abaixo.
#url_schema: zcat /usr/share/doc/zabbix-sql-scripts/mysql/create.sql.gz | mysql -h "{{ zbx_db }}" -u "{{ db_user_server }}"  "{{ db_name }}"

#-----------------------------------------------------------------------------------------------------#

# Criar usuario no sistema operacional
username_so: mario
userpass_so: 4linux@!
super_group_so: root

# Variaveis de login API Zabbix , Segurança Criar um Usuario no Frontend do Zabbix para Acesso somente API.
username: 'Admin'
password: 'zabbix'

# Declarar as variavies do arquivo de hosts / Alterar IP conforme sua necessidade .
zbx_front: 192.168.3.100
zbx_srv: 192.168.3.110
zbx_db: 192.168.3.120
zbx_proxy: 192.168.3.130

#--------------------------- Adção de templates -----------------------------------------------------#
# Macro Padronizada adição de Templates no Agentes 
zabbix_link_templates:
  - Linux by Zabbix agent active
  - ICMP Ping


# VARIAVEL CRIAÇÃDO DO USUARIO ZABBIX LOCALHOST
db_user_zabbix: 'zabbix'
db_user_zabbix_pass: 'zabbix'

# SENHA DO USER LOCAL ROOT
root_pass: 'zabbix'

# VARIAVEL DE TimeZone.
timezone: America/Sao_Paulo

database_remove:
  - test
  - sys
  - perfomance_schema 

# VARIAVEL CRIAÇÃO DO BANCO DE DADOS
db_name: 'zabbix'

# VARIAVEL CRIAÇÃO DO USUARIO ZABBIX SERVER
db_user_server: 'zabbix_server'
db_user_pass_server: 'zabbix'

# VARIAVEIS DE CRIAÇÃO DE USUARIO zabbix_web
db_user_web: 'zabbix_web'
db_user_pass_web: 'zabbix'

# VARIAVEIS DE CRIAÇÃO DE USUARIO ZABBIXMONITDB
db_user_monit_db: 'zabbixmonitdb'
db_user_pass_db: 'zabbixmonitdb'

#------------------------------------------------------------------------------------------------------#
# Variaveis de monitoring db zabbix
# Ajustar conforme sua versão de banco de dados Acessando e verificando versão com comando select version ();
# https://downloads.mysql.com/archives/c-odbc/

version_connector_odbc: 8.0.26
FRONT_DSN: zabbix

#Observação Neste caso do Monitoramento no host banco dados a partir do proxy, podera seguir conforme
# Sua Necessidade e alterando assim, podendo clonar host e adcionar template MYSQL by Zabbix agent2
# Variveis do host User password criado em deploy.zabbix.yml , verificar usuario abaixo adcionado.
# nosso Caso de Exemplo- ZABBIXMONITDB - Informações o usuario remote acima.

# Acionar variaveis aos hosts.

  # {$MYSQL.DSN} - tcp://192.168.3.120:3306
  # {$MYSQL.PASSWORD} -  zabbixmonitdb
  # {$MYSQL.USER} - zabbixmonitdb
