---
# tasks file for zabbix_ha_server

# -------------------------------------------------------------------------------------------#
- name: Adcionando Repositorio Zabbix Server - {{ ansible_all_ipv4_addresses[0]}}.
  dnf:
    name: https://repo.zabbix.com/zabbix/{{ zbx_version }}/rhel/8/x86_64/zabbix-release-{{ zbx_version }}-1.el8.noarch.rpm
    state: present
  tags: zabbix_server
# --------------------------------------------------------------------------------------------#
- name: Instalando pacotes zabbix-server
  dnf:
    name: '{{ packages_zabbix_server}}'
    state: latest
  tags: zabbix_server
# --------------------------------------------------------------------------------------------#
- name: Iniciar/ Habilitar zabbix-server
  systemd:
    name: zabbix-server
    state: started
    enabled: yes
  tags: zabbix_server
#-------------------------------------------------------------------------------#
- name: Setando configurações de segurança no arquivo zabbix_server.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_server.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: '# DBHost=localhost', line: 'DBHost={{ zbx_db }}' }
    - { regexp: 'DBName=zabbix', line: 'DBName={{ db_name }}' }
    - { regexp: 'DBUser=zabbix', line: 'DBUser={{ db_user_server }}' }
    - { regexp: '# DBPassword=', line: 'DBPassword={{ db_user_pass_server }}' }
    - { regexp: '# StartPollers=5', line: 'StartPollers=10' }
    - { regexp: '# StartPingers=1', line: 'StartPingers=10' }
    - { regexp: '# CacheSize=8M', line: 'CacheSize=1024M' }
    - { regexp: '# Timeout=3', line: 'Timeout=30' }
    - { regexp: '# ValueCacheSize=8M', line: 'ValueCacheSize=1024M' }
    - { regexp: '# VMwareCacheSize=8M', line: 'VMwareCacheSize=1024M' }
    - { regexp: '# StartReportWriters=0', line: 'StartReportWriters=1' }
    - { regexp: '# DBTLSConnect=', line: 'DBTLSConnect=required' }
    - { regexp: '# WebServiceURL=', line: 'WebServiceURL=http://{{zbx_front}}:10053/report' }
    - { regexp: '# HANodeName=', line: 'HANodeName={{ zbx_front }}' }
    - { regexp: '# NodeAddress=localhost:10051', line: 'NodeAddress={{ zbx_front }}:10051' }
  tags: zabbix_server
#-----------------------------------------------------------------------------------#
- name: Adcionado Porta firewalld  Zabbix_Server/Zabbix_Agent2
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10051/tcp
    - 10050/tcp
    - 3306/tcp  
  tags: zabbix_server
# ----------------------------------------------------------------------------------------------#
- name: Reload no firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  tags: zabbix_server
#-------------------------------------------------------------------------------------------------#
- name: Iniciar/ Restart Zabbix-Server / Agent2
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - zabbix-server
  tags: zabbix_server
#----------------------------------------------------------------------------------------------#
