#------------------- Instalação zabbix Server ------------------------#
- name: Deploy de Instalação Zabbix Server tree layers.
  hosts:
    - zabbix 
    
  roles:
    - role: Common_Linux
    - role: zabbix_db
      when: ansible_host == zbx_db
    - role: zabbix_server
      when: ansible_host == zbx_srv
    - role: zabbix_front
      when: ansible_host == zbx_front
    - role: grafana_server
      when: ansible_host == zbx_front

#----------------------- PROXY SP --------------------------------------#
- name: Instalação do Zabbix Proxy SP
  hosts: 
    - zbx_proxy_sp
  vars:
   - proxy_name: 'PROXY-SP'
   - zbx_proxy: 192.168.3.130
   - host_grupo: Empresa-X
   - psk_identity: proxysp
   - proxy_db: sp.db
   - local: sp
  roles:
    - role: zabbix_proxy
#---------------------------------------------------------------------#
- name: Playbook de instalação do Agentes Zabbix .
  hosts:
    - zbx_front
    - zbx_db
  vars:
    - proxy_name: 'PROXY-SP'
    - zbx_proxy: 192.168.3.130
    - host_grupo: Empresa-X
  roles:
    - role: zabbix_agent_linux
#----------------------------------------------------------------------#

- name: Instalação do Zabbix Proxy RJ.
  hosts: 
    - zbx_proxy_rj
    
  vars:
   - proxy_name: 'PROXY-RJ'
   - zbx_proxy: 192.168.3.140
   - host_grupo: Empresa-Y
   - psk_identity: proxyrj
   - proxy_db: rj.db
   - local: rj
  
  roles:
    - role: zabbix_proxy
#-----------------------------------------------------------------------#

- name: Deploy Instalação Agente windows .
  hosts:
    - DC01
    
  vars:
    - zbx_front: 192.168.3.100
    - proxy_name: 'PROXY-SP'
    - zbx_proxy: 192.168.3.130
    - host_grupo: Empresa-X
    
  roles:
    - role: zabbix_agent_windows

- name: Playbook de instalação do Agente Windows .
  hosts:
    - DC02
    
  vars:
    - zbx_front: 192.168.3.100
    - proxy_name: 'PROXY-RJ'
    - zbx_proxy: 192.168.3.140
    - host_grupo: Empresa-Y
    
  roles:
    - role: zabbix_agent_windows

#-----------------------------------------------------------------------#
