- name: Instalação do Zabbix Proxy
  hosts: 
    - zbx_proxy_sp
  
  vars:

   - proxy_name: 'PROXY-SP'
   - zbx_proxy: 192.168.3.130
   - host_grupo: Matriz-A
   - psk_identity: proxysp
   - proxy_db: sp.db
   - local: sp

  roles:
    - role: zabbix_proxy 
