---

- name: "Windows | Set path to zabbix.exe"
  set_fact:
    zabbix_win_exe_path: '{{ zabbix_win_install_dir }}\bin\zabbix_agent2.exe'

- name: "Windows | Set variables specific to Zabbix 4.0"
  set_fact:
    zabbix_win_package: '{{ zabbix_win_package }}'
    zabbix_win_exe_path: '{{ zabbix_win_install_dir }}\bin\zabbix_agent2.exe'
  when:
    - zabbix_version_long is version('4.0.0', '>=')

- name: "Windows | Check if Zabbix agent is present"
  win_stat:
    path: '{{ zabbix_win_exe_path }}'
  register: agent_file_info

- name: "Windows | Get Installed Zabbix Agent Version"
  win_file_version:
    path: "{{ zabbix_win_exe_path }}"
  register: zabbix_win_exe_info
  when:
    - agent_file_info.stat.exists

- name: "Windows | Checking Update (Set default)"
  set_fact:
    update_zabbix_agent: False
  when:
    - agent_file_info.stat.exists

- name: "Windows | Checking Update"
  set_fact:
    update_zabbix_agent: True
  when:
    - agent_file_info.stat.exists
    - zabbix_win_exe_info.win_file_version.product_version is version(zabbix_version_long, '<')
    - zabbix_agent_package_state == 'latest'

- name: "Windows | Stop Zabbix (Update)"
  win_service:
    name: Zabbix Agent
    start_mode: auto
    state: stopped
  when:
    - update_zabbix_agent | default(false)
    - agent_file_info.stat.exists

- name: Parando Serviço 
  win_service:
    name: Zabbix Agent 2
    state: stopped
  when:
    - update_zabbix_agent | default(false)
    - agent_file_info.stat.exists
  ignore_errors: yes


- name: Remove Serviço zabbix agent2
  win_command: '{{ zabbix_win_exe_path }} --config {{ zabbix_win_install_dir }}\conf\zabbix_agent2.conf --uninstall'
  when:
    - update_zabbix_agent | default(false)
    - agent_file_info.stat.exists
  ignore_errors: yes


- name:  Removendo estrutura do diretorio
  win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ zabbix_win_install_dir }}"
    - "{{ zabbix_win_userparameters }}"
    - "{{ zabbix_win_scripts }}"
    - "{{ zabbix_win_log }}"
  when:
    - update_zabbix_agent | default(false)
    - agent_file_info.stat.exists


- name:  Criando estrutura Diretorio
  win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ zabbix_win_install_dir }}"
    - "{{ zabbix_win_userparameter }}"
    - "{{ zabbix_win_log }}"
  

- name: Download Zabbix Agent Zip file
  win_get_url:
    url: '{{zabbix_win_download_link }}'
    dest: '{{ zabbix_win_install_dir }}'
    force: False
    follow_redirects: all
  register: zabbix_agent_win_download_zip
  until: zabbix_agent_win_download_zip is succeeded


- name: "Windows | Unzip file"
  win_unzip:
    src: '{{ zabbix_win_install_dir }}\{{ zabbix_win_package }}'
    dest: "{{ zabbix_win_install_dir }}"
    creates: '{{ zabbix_win_exe_path }}'

- name: "Windows | Instalando Serviço no Windows"
  win_command: '{{ zabbix_win_exe_path }} --config {{ zabbix_win_install_dir }}\conf\zabbix_agent2.conf --install'
  register: zabbix_windows_install
  ignore_errors: yes

- name: Copiando template Agent para Servidor.
  win_template:
    src: zabbix_agent2.conf
    dest: '{{ zabbix_win_install_dir }}\conf\zabbix_agent2.conf'

- name: Started o service
  win_service:
    name: Zabbix Agent 2
    start_mode: auto
    state: started
  ignore_errors: yes

- name: "Windows | Getting Zabbix Service Recovery Settings"
  win_shell: sc.exe qfailure "Zabbix Agent" 1100
  register: svc_recovery
  changed_when: false
  check_mode: false
  when: zabbix_agent_win_svc_recovery

- name: "Windows | Setting Zabbix Service Recovery"
  win_shell: sc.exe failure "Zabbix Agent" actions= restart/5000/restart/10000/restart/20000 reset= 86400
  when:
    - "'RESTART -- Delay' not in svc_recovery.stdout"
    - zabbix_agent_win_svc_recovery

- name: "Windows | Add Porta Zabbix Firewall rule "
  win_firewall_rule:
    name: Zabbix Agent
    localport: 10050
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
  ignore_errors: yes

- name : Remover Arquivo zipado Pasta.
  win_shell: del '{{ zabbix_win_install_dir }}\{{ zabbix_win_package }}' 
  ignore_errors: yes

...
