---

# defaults file for update_linux

# Variaveis de Playbook 

timezone: America/Sao_Paulo

common_pacotes_redhat:
  - firewalld
  - bind-utils
  - bc
  - bzip2
  - curl
  - elinks
  - git
  - htop
  - iperf3
  - iptraf
  - lsof
  - lynx
  - mtr
  - net-tools
  - nmap
  - pv
  - screen
  - tcpdump
  - telnet
  - unzip
  - vim
  - wget
  - aspell
  - bash-completion
  - tree
  - chrony
  - python3

common_pacotes_debian:
  - build-essential
  - net-tools
  - bc
  - sudo
  - screen
  - tcpdump
  - telnet
  - nmap
  - vim
  - tree
  - chrony
  - bash-completion

# variavel de Senha do Usuario Ansible
#ansible_pass: "74094276cfbf400d991af276008d94a4"
