---
# tasks file for install_zabbix_front

# -------------------------------------------------------------------------------------------#
- name: FRONT | Adcionando Repositorio Zabbix - CentOS8
  dnf:
    name: '{{ url_packages_zabbix }}'
    state: present
  tags: zabbix_front
  when: ansible_facts['distribution_major_version'] == "8"
# --------------------------------------------------------------------------------------------#
#
- name: FRONT | Instalando pacotes zabbix-Frontend
  dnf:
    name: "{{ packages_zabbix_frontend }}"
    state: latest
  tags: zabbix_front
  when: ansible_facts['distribution_major_version'] == "8"
#----------------------------------------------------------------------------------------------#
- name: PHP | ADD time zone no /etc/php-fpm.d/zabbix.conf
  shell: "echo php_value[date.timezone] = {{ timezone }} >> /etc/php-fpm.d/zabbix.conf"
  ignore_errors: True
  tags: zabbix_front
  when: ansible_facts['distribution_major_version'] == "8"
#-----------------------------------------------------------------------------------------------#
- name: FRONT | Copiando Arquivo zabbix.conf.php default
  template:
    src:  templates/zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
  tags: config_inicial
  when: ansible_facts['distribution_major_version'] == "8"
# ----------------------------------------------------------------------------------------------#
- name: PHP | Iniciar/ Habilitar e Iniciar App do Apache2
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
     - httpd 
     - php-fpm
  tags: zabbix_front
  when: ansible_facts['distribution_major_version'] == "8"
#----------------------------------------------------------------------------------------------#
- name: FRONT | Adcionado Porta firewalld  Front/Apache2/Zabbix_Server/Zabbix_Agent2
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
   - 10051/tcp
   - 10050/tcp
   - 3306/tcp
   - 80/tcp
   - 443/tcp
  tags: zabbix_front
  when: ansible_facts['distribution_major_version'] == "8"
# ----------------------------------------------------------------------------------------------#
- name: Reload no firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  tags: zabbix_front
#-----------------------------------------------------------------------------------------------#
- name: FRONT | Reinciar FRONTEND
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - php-fpm
    - httpd 
  tags: zabbix_front
  when: ansible_facts['distribution_major_version'] == "8"

#-------------------------------------------------------------------------------------------------#
- name: FRONT | Baixando Pacotes googlechrome 
  shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
  tags: zabbix_front
  when: ansible_facts['distribution_major_version'] == "8"
#-------------------------------------------------------------------------------------------------#
- name: FRONT | Instalando googlechrome
  shell: "sudo dnf localinstall google-chrome-stable_current_x86_64.rpm -y"
  tags: zabbix_front
  when: ansible_facts['distribution_major_version'] == "8"
