---
# tasks file for install_zabbix_front

# -------------------------------------------------------------------------------------------#
- name: Adcionando Repositorio Zabbix - CentOS8
  dnf:
    name: '{{ url_packages_zabbix }}'
    #name: 'http://repo.zabbix.com/zabbix/5.5/rhel/8/x86_64/zabbix-release-5.5-1.el8.noarch.rpm'
    state: present
  tags: zabbix_front
# --------------------------------------------------------------------------------------------#
#
- name: Zabbix | Instalando pacotes zabbix-Frontend
  dnf:
    name: "{{ packages_zabbix_frontend }}"
    state: latest
  tags: zabbix_front
  when: ansible_distribution == "CentOS"
#----------------------------------------------------------------------------------------------#
- name: PHP | ADD time zone no /etc/php-fpm.d/zabbix.conf
  shell: "echo php_value[date.timezone] = {{ timezone }} >> /etc/php-fpm.d/zabbix.conf"
  ignore_errors: True
  tags: zabbix_front
  when: ansible_distribution == "CentOS"
#-----------------------------------------------------------------------------------------------#
- name: zabbix-Frontend | Copiando Arquivo zabbix.conf.php default
  template:
    src:  templates/zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
  tags: config_inicial
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
# ----------------------------------------------------------------------------------------------#
- name: PHP | Iniciar/ Habilitar e Iniciar App do Apache2
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
     - httpd 
     - php-fpm
  tags: zabbix_front
  when: ansible_distribution == "CentOS"
#----------------------------------------------------------------------------------------------#
- name: Adcionado Porta firewalld  Apache2/Zabbix_Server/Zabbix_Agent
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10051/tcp
    - 10050/tcp
    - 3306/tcp
    - 80/tcp
    - 443/tcp
  tags: zabbix_front
  when: ansible_distribution == "CentOS"
# ----------------------------------------------------------------------------------------------#
- name: Reload no firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  tags: zabbix_front
#-----------------------------------------------------------------------------------------------#
- name: Zabbix | Iniciar/ Habilitar zabbix-agent2
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - php-fpm
    - httpd 
  tags: zabbix_front
  when: ansible_distribution == "CentOS"
#----------------------------------------------------------------------------------------------#
