---

# tasks file for install_zabbix_agent_linux

- name: Adcionando Repositorio Zabbix - Rocky Linux 8 
  dnf:
    name: "{{ url_packages_zabbix }}"
    state: present
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# --------------------------------------------------------------------------------------------#
#
- name: Instalando pacote zabbix-agent2
  dnf:
    name: zabbix-agent2
    state: present
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# # --------------------------------------------------------------------------------------------#
- name: SSH | Setando configurações de segurança no arquivo zabbix_agent2.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: "^Server=127.0.0.1", line: "Server={{ zbx_proxy }}" }
    - { regexp: "^ServerActive=127.0.0.1", line: "ServerActive={{ zbx_proxy }} " }
    - { regexp: "^Hostname=Zabbix server", line: "Hostname={{ ansible_fqdn }}" }
    - { regexp: "# Timeout=3", line: "Timeout=30" }
    - { regexp: "# DenyKey=system.run[*]", line: "AllowKey=system.run[*]" }
    # Modo Ativo habilitar opção abaixo.
    - { regexp: '# TLSConnect=unencrypted', line: 'TLSConnect=psk' }
    - { regexp: '# TLSPSKIdentity=', line: 'TLSPSKIdentity=zabbix' }
    - { regexp: '# TLSPSKFile=', line: 'TLSPSKFile=/etc/zabbix/keys/agent.psk' }
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#----------------------------------------------------------------------------------------------#
- name: Adcionado Porta firewalld  Zabbix_Agent2
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10050/tcp
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# ----------------------------------------------------------------------------------------------#
- name: Iniciar/ Habilitar zabbix-agent2
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#-------------------------------------------------------------------------------#
- name: Reload no firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# -------------------------------------------------------------------------------------------#
# -------------------------------------------------------------------------------------------#
- name: Criar diretorio chave PSK
  file:
    path: /etc/zabbix/keys
    owner: zabbix
    group: zabbix
    mode: '700'
    state: directory
    recurse: yes
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# # --------------------------------------------------------------------------------------------#
- name: Gerando Chave psk - ZBX AGT
  shell: sudo sh -c "openssl rand -hex 64 > /etc/zabbix/keys/agent.psk"
  ignore_errors: true
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# #-----------------------------------------------------------------------------------------------#
- name: Mudando Permissão para Zabbix da chave psk
  shell: sudo chown zabbix:zabbix /etc/zabbix/keys/agent.psk
  ignore_errors: True
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# #------------------------------------------------------------------------------------------------#
- name : Mudando Permissao chmod zabbix
  shell: sudo chmod 500 /etc/zabbix/keys/agent.psk
  ignore_errors: True
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# #------------------------------------------------------------------------------------------------#
- name : Armazenando psk VARIAVEL
  shell: "cat /etc/zabbix/keys/agent.psk"
  register: pks
  ignore_errors: yes
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#------------------------------------------------------------------------------------------------#
- name: Armazenando saida pks.stdout
  set_fact: 
       psk: "{{ pks.stdout }}"
#-------------------------------------------------------------------------------------------------#
- name: Criando hosts no zabbix forma Automatica.
  local_action:
    module: community.zabbix.zabbix_host
    server_url: '{{ url_zabbix_api }}'
    login_user: '{{ username }}'
    login_password: '{{ password }}'
    host_name: "{{ansible_fqdn}}"
    visible_name: "{{ansible_fqdn}}"
    host_groups:
      - '{{ host_grupo }}'
    link_templates: '{{ host_template }}'
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: '1'
        main: 1
        useip: 1
        ip: "{{ ansible_all_ipv4_addresses[0]}}"
        dns: ""
        port: "10050"
    proxy: '{{ proxy_name }}'
    tls_connect: 2  
    tls_accept: 1
    tls_psk_identity: 'zabbix'
    tls_psk: "{{ psk }}"  
    validate_certs: yes
  tags: api_zabbix
  when: ansible_facts['distribution_major_version'] == "8"

...