---
# tasks file for install_zabbix_agent_linux

- name: Adcionando Repositorio Zabbix - Rocky Linux 8 
  dnf:
    name: "{{ url_packages_zabbix }}"
    state: present
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# --------------------------------------------------------------------------------------------#
#
- name: Instalando pacote zabbix-agent2
  dnf:
    name: zabbix-agent2
    state: present
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# # --------------------------------------------------------------------------------------------#
- name: Iniciar/ Habilitar zabbix-agent2
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#----------------------------------------------------------------------------------------------#
- name: Adcionado Porta firewalld  Zabbix_Agent2
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10050/tcp
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#-------------------------------------------------------------------------------#
- name: SSH | Setando configurações de segurança no arquivo zabbix_agent2.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: "^Server=127.0.0.1", line: "Server={{ zbx_proxy}}" }
    - { regexp: "^ServerActive=127.0.0.1", line: "ServerActive={{ zbx_proxy }} " }
    - { regexp: "^Hostname=Zabbix server", line: "Hostname={{ ansible_fqdn }}" }
    - { regexp: "# Timeout=3", line: "Timeout=30" }
    - { regexp: "# DenyKey=system.run[*]", line: "AllowKey=system.run[*]" }
  when: ansible_facts['distribution_major_version'] == "8"
  tags: zabbix_agent2
# ----------------------------------------------------------------------------------------------#
- name: Realizar Restart zabbix-agent2
  systemd:
    name: zabbix-agent2
    state: restarted
    enabled: yes
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#------------------------------------------------------------------------------------------------#

- name: Reload no firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# -------------------------------------------------------------------------------------------#

