---

# tasks file for install_zabbix_agent_linux

- name: Adcionando Repositorio Zabbix - Rocky Linux 8 
  dnf:
    name: https://repo.zabbix.com/zabbix/{{ zbx_version }}/rhel/8/x86_64/zabbix-release-{{ zbx_version }}-1.el8.noarch.rpm
    state: present
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# --------------------------------------------------------------------------------------------#
#
- name: Instalando pacote zabbix-agent2
  dnf:
    name: zabbix-agent2
    state: present
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# # --------------------------------------------------------------------------------------------#
- name: Setando configurações de segurança no arquivo zabbix_agent2.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: "^Server=127.0.0.1", line: "Server={{ zbx_proxy }}" }
    - { regexp: "^ServerActive=127.0.0.1", line: "ServerActive={{ zbx_proxy }} " }
    - { regexp: "^Hostname=Zabbix server", line: "Hostname={{ ansible_fqdn }}" }
    - { regexp: "# Timeout=3", line: "Timeout=30" }
    - { regexp: "# DenyKey=system.run[*]", line: "AllowKey=system.run[*]" }
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#----------------------------------------------------------------------------------------------#
- name: Adcionado Porta firewalld  Zabbix_Agent2
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10050/tcp
    - 10051/tcp
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# ----------------------------------------------------------------------------------------------#
- name: Iniciar/ Habilitar zabbix-agent2
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#-------------------------------------------------------------------------------#
- name: Reload no firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#-------------------------------------------------------------------------------------------------#
- name: Criando hosts no zabbix forma Automatica.
  local_action:
    module: community.zabbix.zabbix_host
    server_url: http://{{ zbx_front }}/zabbix/
    login_user: '{{ username }}'
    login_password: '{{ password }}'
    host_name: "{{ansible_fqdn}}"
    visible_name: "{{ansible_fqdn}}"
    host_groups:
      - '{{ host_grupo }}'
    link_templates:
#      - '{{ host_template }}'
          - Linux by Zabbix agent active
          - ICMP Ping
          - Apache by Zabbix agent
#      - '{{ host_template }}'
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: '1'
        main: 1
        useip: 1
        ip: "{{ ansible_all_ipv4_addresses[0]}}"
        dns: ""
        port: "10050"
    proxy: '{{ proxy_name }}'
  tags: api_zabbix
  when: ansible_facts['distribution_major_version'] == "8"

...
