---

# tasks file for install_zabbix_agent_linux

- name: Adcionando Repositorio Zabbix - {{ ansible_distribution }}/{{ ansible_all_ipv4_addresses[0]}}.
  dnf:
    name: https://repo.zabbix.com/zabbix/{{ zbx_agent_version }}/rhel/8/x86_64/zabbix-release-{{ zbx_agent_version }}-1.el8.noarch.rpm
    state: present
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# --------------------------------------------------------------------------------------------#
#
- name: Instalando pacote zabbix-agent2 - {{ ansible_all_ipv4_addresses[0]}}.
  dnf:
    name: zabbix-agent2
    state: present
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# # --------------------------------------------------------------------------------------------#
- name: Configurando o Arquivo zabbix_agent2.conf - {{ ansible_all_ipv4_addresses[0]}}.
  lineinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: "^Server=127.0.0.1", line: "Server={{ zbx_proxy }}" }
    - { regexp: "^ServerActive=127.0.0.1", line: "ServerActive={{ zbx_proxy }} " }
    - { regexp: "^Hostname=Zabbix server", line: "Hostname={{ ansible_fqdn }}" }
    - { regexp: "# Timeout=3", line: "Timeout=30" }
    - { regexp: "# DenyKey=system.run[*]", line: "AllowKey=system.run[*]" }
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#----------------------------------------------------------------------------------------------#
- name: Adcionado Porta firewalld  Zabbix_Agent2 - {{ ansible_all_ipv4_addresses[0]}}.
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10050/tcp
    - 10051/tcp
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
# ----------------------------------------------------------------------------------------------#
- name: Iniciar/ Habilitar zabbix-agent2 - {{ ansible_all_ipv4_addresses[0]}}.
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#-------------------------------------------------------------------------------#
- name: Reload no firewalld - {{ ansible_all_ipv4_addresses[0]}}.
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"

...
