---
# handlers file for grafana-server

#----------------------------------------------------------------------------------------------#
- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes
  tags: zabbix_server