---
# vars file for zabbix-proxy

url_packages_zabbix: http://repo.zabbix.com/zabbix/5.5/rhel/8/x86_64/zabbix-release-5.5-1.el8.noarch.rpm

# VARIAVEL HOSTNAME DO ZABBIX PROXY
 
# PACOTES DE INSTALL PROXY
packages_zabbix_proxy: zabbix-proxy-sqlite3
packages_zabbix_agent: zabbix-agent2