---
# tasks file for grafana-server
# -------------------------------------------------------------------------------------------#
- name: Adcionando Repositorio Grafana Server
  shell: "wget https://dl.grafana.com/oss/release/grafana-{{ version_grafana }}-1.x86_64.rpm"
  tags: grafana-server
# --------------------------------------------------------------------------------------------#
- name: Atualizando Sistema / cache Sistema Operacional
  dnf: 
    name: '*'
    state: latest
    update_cache: yes
  tags: config_inicial
#----------------------------------------------------------------------------------------------#
- name: Instalando pacotes grafana-server
  shell: "yum install grafana-{{ version_grafana }}-1.x86_64.rpm -y"
  tags: grafana-server
#------------------------------------------------------------------------------------------------#
- name: Instalando Plugins no Grafana
  grafana_plugin:
    name: "{{ item }}"
    version: latest
    state: present
  loop:
    - alexanderzobnin-zabbix-app
    - grafana-piechart-panel
  tags: grafana-server
#----------------------------------------------------------------------------------------------#
- name: Iniciar/ Habilitar Grafana-server
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes
  tags: zabbix_server
#----------------------------------------------------------------------------------------------#
- name: Criando Datasource do zabbix no Grafana
  grafana_datasource:
    name: "zabbix"
    grafana_url: "http://{{ zbx_front }}:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    ds_type: "alexanderzobnin-zabbix-datasource"
    ds_url: "http://{{ zbx_front }}/zabbix/api_jsonrpc.php"
    database: "zabbix"
  tags: grafana-server
#----------------------------------------------------------------------------------------------#
- name: Liberando Porta firewall.
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 3000/tcp
  tags: grafana-server
# ----------------------------------------------------------------------------------------------#
- name: Reload no firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  tags: grafana-server
...