---

# defaults file for update_linux

# Variaveis de Playbook 

timezone: America/Sao_Paulo

common_pacotes_redhat:
  - firewalld
  - bind-utils
  - bc
  - bzip2
  - curl
  - git
  - iperf3
  - iptraf
  - lsof
  - mtr
  - net-tools
  - nmap
  - tcpdump
  - telnet
  - unzip
  - vim
  - wget
  - bash-completion
  - tree
  - chrony
  - python3

common_pacotes_debian:
  - build-essential
  - net-tools
  - bc
  - sudo
  - screen
  - tcpdump
  - telnet
  - nmap
  - vim
  - tree
  - chrony
  - bash-completion

# variavel de Senha do Usuario Ansible
ansible_pass: "2924476eb3289c610b2a2e40bb60a9e0"
