---
# defaults file for Common_RockyLinux


timezone: America/Sao_Paulo

common_pacotes_redhat:
  - firewalld
  - bind-utils
  - bc
  - bzip2
  - curl
  - git
  - iperf3
  - iptraf
  - lsof
  - mtr
  - net-tools
  - nmap
  - tcpdump
  - telnet
  - unzip
  - vim
  - wget
  - bash-completion
  - tree
  - chrony
  - python3
  - traceroute
  
