---
# tasks file for zabbix-proxy
- name: Adcionando Repositorio Zabbix Proxy - {{ ansible_all_ipv4_addresses[0]}}.
  dnf:
    name: https://repo.zabbix.com/zabbix/{{ zbx_version }}/rhel/8/x86_64/zabbix-release-{{ zbx_version }}-1.el8.noarch.rpm
    state: present
  ignore_errors: yes
  tags: zabbix_proxy
# --------------------------------------------------------------------------------------------#
- name: Instalando pacotes zabbix-proxy
  dnf: name='{{ packages_zabbix_proxy }}' state=latest
  tags: zabbix_proxy
#--------------------------------------------------------------------------------------------#
- name: Criar diretorio banco sqlite3
  file:
    path: /var/lib/sqlite
    owner: zabbix
    group: zabbix
    mode: '0755'
    state: directory
    recurse: yes
  tags: zabbix_proxy
# --------------------------------------------------------------------------------------------#
- name: Gerando Chave psk
  shell: sudo sh -c "openssl rand -hex 32 > /etc/zabbix/{{ local }}.psk"
  ignore_errors: true
  tags: zabbix_proxy
#------------------------------------------------------------------------------------------------#
- name : Armazenando psk VARIAVEL
  shell: "cat /etc/zabbix/{{ local }}.psk"
  register: pks
  ignore_errors: yes
  tags: zabbix_proxy
#------------------------------------------------------------------------------------------------#
- name: Armazenando saida pks.stdout
  set_fact: 
       psk: "{{ pks.stdout }}"
#------------------------------------------------------------------------------------------------#
- name: SSH | Setando configurações de segurança no arquivo zabbix_proxy.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_proxy.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: '# ProxyMode=0', line: 'ProxyMode=0' }
    - { regexp: '^Server=127.0.0.1', line: 'Server={{ allonezbx }}' }
    - { regexp: '^Hostname=Zabbix proxy', line: 'Hostname={{ proxy_name }}' }
    - { regexp: '# EnableRemoteCommands=0', line: 'EnableRemoteCommands=1' }
    - { regexp: '^DBName=zabbix_proxy', line: 'DBName=/var/lib/sqlite/{{ proxy_db }}' }
    - { regexp: '# StartPollers=5', line: 'StartPollers=10' }
    - { regexp: '# StartPinger=1', line: 'StartPinger=10' }
    - { regexp: '# ConfigFrequency=3600', line: 'ConfigFrequency=60' }
    - { regexp: '# CacheSize=8M', line: 'CacheSize=256M' }
    - { regexp: '# HistoryCacheSize=16M', line: 'HistoryCacheSize=256M' }
    - { regexp: '^Timeout=4', line: 'Timeout=30' }
    - { regexp: '# StartPingers=1', line: 'StartPingers=10' }
    - { regexp: '# TLSConnect=unencrypted', line: 'TLSConnect=psk' }
    - { regexp: '# TLSAccept=unencrypted', line: 'TLSAccept=psk' }
    - { regexp: '# TLSPSKIdentity=', line: 'TLSPSKIdentity={{ psk_identity }}' }
    - { regexp: '# TLSPSKFile=', line: 'TLSPSKFile=/etc/zabbix/{{ local }}.psk' }
  tags: zabbix_proxy
#-----------------------------------------------------------------------------------------------#
- name: Restart do  Zabbix Proxy
  systemd: name=zabbix-proxy state=started enabled=yes
  tags: zabbix_proxy 
#----------------------------------------------------------------------------------------------#
- name: Instalando Pacotes Agente2
  dnf: name='{{ packages_zabbix_agent }}' state=latest
  tags: zabbix_proxy
#------------------------------------------------------------------------------------#
- name: Configurando o Arquivo zabbix_agent2.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: "^Server=127.0.0.1", line: "Server={{ zbx_proxy }}" }
    - { regexp: "^ServerActive=127.0.0.1", line: "ServerActive={{ zbx_proxy }} " }
    - { regexp: "^Hostname=Zabbix server", line: "Hostname={{ ansible_fqdn }}" }
    - { regexp: "# Timeout=3", line: "Timeout=30" }
    - { regexp: "# DenyKey=system.run[*]", line: "AllowKey=system.run[*]" }
  tags: zabbix_proxy
#------------------------------------------------------------------------------------------------#
- name: Restart zabbix-agent2
  systemd: name=zabbix-agent2 state=restarted enabled=yes
  tags: zabbix_proxy
#-------------------------------------------------------------------------------------#

- name: Adcionado Porta firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10051/tcp
    - 10050/tcp
    - 3306/tcp
  tags: zabbix_proxy
#----------------------------------------------------------------------------------------------#
- name: Restart do  Zabbix Proxy
  systemd: name=zabbix-proxy state=restarted enabled=yes
  tags: zabbix_proxy 
# ----------------------------------------------------------------------------------------------#
- name: Reload no firewalld
  systemd: name=firewalld state=reloaded daemon_reload=yes enabled=yes
  tags: zabbix_proxy
#------------------------------------------------------------------------------------------------#
- name: Realizando Download dos Drivers odbc versão correspondende do banco
  shell: rpm -ivh https://downloads.mysql.com/archives/get/p/10/file/mysql-connector-odbc-{{ version_connector_odbc }}-1.el8.x86_64.rpm
  ignore_errors: yes
  tags: zabbix_proxy
#------------------------------------------------------------------------------------------------#
- name: Configurando o Arquivo odbc.ini
  blockinfile:
    path: /etc/odbc.ini
    block: |
       [{{ FRONT_DSN }}]
       Description = MySQL Monitoring Database
       Driver      = MySQL ODBC 8.0 Unicode Driver
       Server      = {{ zbx_db }}
       User        = {{ db_user_monit_db }}
       Password    = {{ db_user_pass_db }}
       Port        = 3306
       Database    = zabbix
  tags: zabbix_proxy