---
# tasks file for zabbix-proxy
- name: Adcionando Repositorio Zabbix Proxy.
  dnf:
    name: https://repo.zabbix.com/zabbix/{{ zbx_version }}/rhel/8/x86_64/zabbix-release-{{ zbx_version }}-1.el8.noarch.rpm
    state: present
  ignore_errors: yes
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
# --------------------------------------------------------------------------------------------#
#
- name: Instalando pacotes zabbix-proxy
  dnf: name='{{ packages_zabbix_proxy }}' state=latest
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#--------------------------------------------------------------------------------------------#
- name: Criar diretorio banco sqlite3
  file:
    path: /var/lib/sqlite
    owner: zabbix
    group: zabbix
    mode: '0755'
    state: directory
    recurse: yes
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
# --------------------------------------------------------------------------------------------#
- name: Gerando Chave psk - ZBX - ZBX PROXY
  shell: sudo sh -c "openssl rand -hex 32 > /etc/zabbix/proxy.psk"
  ignore_errors: true
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"

#------------------------------------------------------------------------------------------------#
- name : Armazenando psk VARIAVEL
  shell: "cat /etc/zabbix/proxy.psk"
  register: pks
  ignore_errors: yes
  when: ansible_facts['distribution_major_version'] == "8"
#------------------------------------------------------------------------------------------------#
- name: Armazenando saida pks.stdout
  set_fact: 
       psk: "{{ pks.stdout }}"
#------------------------------------------------------------------------------------------------#
- name: SSH | Setando configurações de segurança no arquivo zabbix_proxy.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_proxy.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: '# ProxyMode=0', line: 'ProxyMode=0' }
    - { regexp: '^Server=127.0.0.1', line: 'Server={{ zbx_srv }}' }
    - { regexp: '^Hostname=Zabbix proxy', line: 'Hostname={{ proxy_name }}' }
    - { regexp: '# EnableRemoteCommands=0', line: 'EnableRemoteCommands=1' }
    - { regexp: '^DBName=zabbix_proxy', line: 'DBName=/var/lib/sqlite/zabbix_proxy.db' }
    - { regexp: '# StartPollers=5', line: 'StartPollers=10' }
    - { regexp: '# StartPinger=1', line: 'StartPinger=10' }
    - { regexp: '# ConfigFrequency=3600', line: 'ConfigFrequency=60' }
    - { regexp: '# CacheSize=8M', line: 'CacheSize=256M' }
    - { regexp: '^Timeout=4', line: 'Timeout=30' }
    - { regexp: '# TLSConnect=unencrypted', line: 'TLSConnect=psk' }
    - { regexp: '# TLSAccept=unencrypted', line: 'TLSAccept=psk' }
    - { regexp: '# TLSPSKIdentity=', line: 'TLSPSKIdentity={{ psk_identity }}' }
    - { regexp: '# TLSPSKFile=', line: 'TLSPSKFile=/etc/zabbix/proxy.psk' }
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#-----------------------------------------------------------------------------------------------#
- name: ZBX PROXY | Realizar Restart do  Zabbix Proxy.
  systemd: name=zabbix-proxy state=started enabled=yes
  tags: zabbix_proxy 
  when: ansible_facts['distribution_major_version'] == "8"
#----------------------------------------------------------------------------------------------#
- name: Instalando pacote zabbix-agent2
  dnf: name='{{ packages_zabbix_agent }}' state=latest
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#------------------------------------------------------------------------------------#
- name: SSH | Setando configurações de segurança no arquivo zabbix_agent2.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: "^Server=127.0.0.1", line: "Server={{ zbx_proxy }}" }
    - { regexp: "^ServerActive=127.0.0.1", line: "ServerActive={{ zbx_proxy }} " }
    - { regexp: "^Hostname=Zabbix server", line: "Hostname={{ ansible_fqdn }}" }
    - { regexp: "# Timeout=3", line: "Timeout=30" }
    - { regexp: "# DenyKey=system.run[*]", line: "AllowKey=system.run[*]" }
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#------------------------------------------------------------------------------------------------#
- name: Restart zabbix-agent2
  systemd: name=zabbix-agent2 state=restarted enabled=yes
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#-------------------------------------------------------------------------------------#

- name: Adcionado Porta firewalld de Comunicação zabbix Proxy.
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10051/tcp
    - 10050/tcp
    - 3306/tcp
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#----------------------------------------------------------------------------------------------#
- name: Realizar Restart do  Zabbix Proxy.
  systemd: name=zabbix-proxy state=restarted enabled=yes
  tags: zabbix_proxy 
  when: ansible_facts['distribution_major_version'] == "8"
# ----------------------------------------------------------------------------------------------#
- name: Reload no firewalld
  systemd: name=firewalld state=reloaded daemon_reload=yes enabled=yes
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#------------------------------------------------------------------------------------------------#
- name: Realizando Download dos Drivers odbc versão correspondende do banco
  shell: rpm -ivh https://downloads.mysql.com/archives/get/p/10/file/mysql-connector-odbc-{{ version_connector_odbc }}-1.el8.x86_64.rpm
  ignore_errors: yes
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#------------------------------------------------------------------------------------------------#
- name: Setando configurações no Arquivo odbc.ini
  blockinfile:
    path: /etc/odbc.ini
    block: |
       [{{ font_dns }}]
       Description = MySQL Monitoring Database
       Driver      = MySQL ODBC 8.0 Unicode Driver
       Server      = {{ zbx_db }}
       User        = {{ user_mysql_remote }}
       Password    = {{ user_mysql_pass_remote }}
       Port        = 3306
       Database    = zabbix
  tags: zabbix_front
  when: ansible_facts['distribution_major_version'] == "8"

#-----------------------------------------------------------------------------------------------#
- name: Criar o Proxy Modo Active.
  local_action:
    module: community.zabbix.zabbix_proxy
    server_url: http://{{ zbx_front }}/zabbix/
    login_user: '{{ username }}'
    login_password: '{{ password }}'
    proxy_name: '{{ proxy_name }}'
    status: active
    state: present
    proxy_address: '{{ zbx_proxy }}'
    tls_accept: PSK
    tls_psk_identity: '{{ psk_identity }}'
    tls_psk: "{{ psk }}"  
  when: ansible_facts['distribution_major_version'] == "8"
#-----------------------------------------------------------------------------------#
- name: Criando Proxy no Frontend do zabbix .
  local_action:
    module: community.zabbix.zabbix_host
    server_url: '{{ url_zabbix_api }}'
    login_user: '{{ username }}'
    login_password: '{{ password }}'
    host_name: "{{ansible_fqdn}}"
    visible_name: "{{ansible_fqdn}}"
    host_groups:
      - '{{ host_grupo }}'
    link_templates:
      - '{{ host_template }}'
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: '1'
        main: 1
        useip: 1
        ip: "{{ ansible_all_ipv4_addresses[0]}}"
        dns: ""
        port: "10050"
    proxy: '{{ proxy_name }}'
  tags: api_zabbix
  when: ansible_facts['distribution_major_version'] == "8"