---
# tasks file for zabbix-proxy
- name: Adcionando Repositorio Zabbix Proxy.
  dnf:
    name: '{{ url_packages_zabbix }}'
    state: present
  ignore_errors: yes
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
# --------------------------------------------------------------------------------------------#
#
- name: Instalando pacotes zabbix-proxy
  dnf:
    name: '{{ packages_zabbix_proxy }}'
    state: latest
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#-------------------------------------------------------------------------------------------------#
#--------------------------------------------------------------------------------------------#
- name: Criar diretorio banco sqlite3
  file:
    path: /var/lib/sqlite
    owner: zabbix
    group: zabbix
    mode: '0755'
    state: directory
    recurse: yes
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
# --------------------------------------------------------------------------------------------#
- name: Gerando Chave psk - ZBX - ZBX PROXY
  shell: sudo sh -c "openssl rand -hex 32 > /etc/zabbix/proxy.psk"
  ignore_errors: true
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"

#------------------------------------------------------------------------------------------------#
- name : Armazenando psk VARIAVEL
  shell: "cat /etc/zabbix/proxy.psk"
  register: pks
  ignore_errors: yes
  when: ansible_facts['distribution_major_version'] == "8"
#------------------------------------------------------------------------------------------------#
- name: Armazenando saida pks.stdout
  set_fact: 
       psk: "{{ pks.stdout }}"
#------------------------------------------------------------------------------------------------#
- name: SSH | Setando configurações de segurança no arquivo zabbix_proxy.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_proxy.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: '# ProxyMode=0', line: 'ProxyMode=0' }
    - { regexp: '^Server=127.0.0.1', line: 'Server={{ zbx_srv }}' }
    - { regexp: '^Hostname=Zabbix proxy', line: 'Hostname={{ proxy_name }}' }
    - { regexp: '# EnableRemoteCommands=0', line: 'EnableRemoteCommands=1' }
    - { regexp: '^DBName=zabbix_proxy', line: 'DBName=/var/lib/sqlite/zabbix_proxy.db' }
    - { regexp: '# StartPollers=5', line: 'StartPollers=10' }
    - { regexp: '# StartPinger=1', line: 'StartPinger=10' }
    - { regexp: '# ConfigFrequency=3600', line: 'ConfigFrequency=60' }
    - { regexp: '# CacheSize=8M', line: 'CacheSize=256M' }
    - { regexp: '^Timeout=4', line: 'Timeout=30' }
    - { regexp: '# TLSConnect=unencrypted', line: 'TLSConnect=psk' }
    #- { regexp: '# TLSAccept=unencrypted', line: 'TLSAccept=psk' }
    - { regexp: '# TLSPSKIdentity=', line: 'TLSPSKIdentity={{ proxy_name}}' }
    - { regexp: '# TLSPSKFile=', line: 'TLSPSKFile=/etc/zabbix/proxy.psk' }
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#-----------------------------------------------------------------------------------------------#
- name: ZBX PROXY | Realizar Restart do  Zabbix Proxy.
  systemd:
    name: zabbix-proxy
    state: restarted
    enabled: yes
  tags: zabbix_proxy 
  when: ansible_facts['distribution_major_version'] == "8"
#----------------------------------------------------------------------------------------------#
- name: Instalando pacote zabbix-agent2
  dnf:
    name: '{{ packages_zabbix_agent }}'
    state: latest
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#------------------------------------------------------------------------------------#
- name: SSH | Setando configurações de segurança no arquivo zabbix_agent2.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: "^Server=127.0.0.1", line: "Server={{ zbx_proxy }}" }
    - { regexp: "^ServerActive=127.0.0.1", line: "ServerActive={{ zbx_proxy }} " }
    - { regexp: "^Hostname=Zabbix server", line: "Hostname={{ ansible_fqdn }}" }
    - { regexp: "# Timeout=3", line: "Timeout=30" }
    - { regexp: "# DenyKey=system.run[*]", line: "AllowKey=system.run[*]" }
    #     # Modo Ativo habilitar opção abaixo.
    # - { regexp: '# TLSConnect=unencrypted', line: 'TLSConnect=psk' }
    #   # Modo Passivo habilitando opção abaixo.
    # - { regexp: '# TLSAccept=unencrypted', line: 'TLSAccept=psk' }
    # - { regexp: '# TLSPSKIdentity=', line: 'TLSPSKIdentity=zabbix_agent' }
    # - { regexp: '# TLSPSKFile=', line: 'TLSPSKFile=/etc/zabbix/keys/agent.psk' }
  tags: zabbix_agent2
  when: ansible_facts['distribution_major_version'] == "8"
#------------------------------------------------------------------------------------------------#
- name: Iniciar/ Habilitar zabbix-agent2
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#-------------------------------------------------------------------------------------#

- name: Adcionado Porta firewalld de Comunicação zabbix Proxy.
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10051/tcp
    - 10050/tcp
    - 3306/tcp
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
# ----------------------------------------------------------------------------------------------#
- name: Reload no firewalld
  systemd: name=firewalld state=reloaded daemon_reload=yes enabled=yes
  tags: zabbix_proxy
  when: ansible_facts['distribution_major_version'] == "8"
#-----------------------------------------------------------------------------------------------#
- name: ZBX PROXY - Criar o Proxy Modo Active.
  local_action:
    module: community.zabbix.zabbix_proxy
    server_url: '{{ url_zabbix_api }}'
    login_user: '{{ username }}'
    login_password: '{{ password }}'
    proxy_name: '{{ proxy_name }}'
    status: active
    state: present
    proxy_address: '{{ zbx_proxy }}'
    tls_accept: PSK
    tls_psk_identity: '{{ zbx_proxy }}'
    tls_psk: "{{ psk }}"  
  when: ansible_facts['distribution_major_version'] == "8"

#-----------------------------------------------------------------------------------#
