# Base create host groups example
- name: Criando Grupo de host no Frontend do Zabbix
  local_action:
    module: community.zabbix.zabbix_group
    server_url: http://{{ allonezbx }}/zabbix/
    login_user: '{{ username }}'
    login_password: '{{ password }}'
    state: present
    host_groups: '{{ host_grupo }}'

- name: Adcionando hosts no zabbix Frontend do Zabbix.
  local_action:
    module: community.zabbix.zabbix_host
    # Alterar variavel correspondente no arquivo iventario
    server_url: http://{{ allonezbx }}/zabbix/
    login_user: '{{ username }}'
    login_password: '{{ password }}'
    host_name: "{{ansible_fqdn}}"
    visible_name: "{{ansible_fqdn}}"
    host_groups:
      - '{{ host_grupo }}'
    link_templates: "{{ zabbix_link_templates }}"
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: '1'
        main: 1
        useip: 1
        ip: "{{ hostvars[inventory_hostname].ansible_host }}"
        #ip: "{{ ansible_all_ipv4_addresses[0]}}"
        dns: ""
        port: "10050"
    proxy: '{{ proxy_name }}'
  register: api_add_front
- debug:
    msg: '{{ api_add_front }}' 
