---

# tasks file for install_zabbix_agent_linux

- name: Adcionando Repositorio Zabbix - {{ ansible_distribution }}
  dnf:
    name: https://repo.zabbix.com/zabbix/{{ zbx_agent_version }}/rhel/8/x86_64/zabbix-release-{{ zbx_agent_version }}-1.el8.noarch.rpm
    state: present
  tags: zabbix_agent2
# --------------------------------------------------------------------------------------------#
- name: Instalando pacote zabbix-agent2 
  dnf:
    name: zabbix-agent2
    state: present
  tags: zabbix_agent2
# --------------------------------------------------------------------------------------------#
- name: Configurando o Arquivo zabbix_agent2.conf 
  lineinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: "^Server=127.0.0.1", line: "Server={{ zbx_proxy }}" }
    - { regexp: "^ServerActive=127.0.0.1", line: "ServerActive={{ zbx_proxy }} " }
    - { regexp: "^Hostname=Zabbix server", line: "Hostname={{ ansible_fqdn }}" }
    - { regexp: "# Timeout=3", line: "Timeout=30" }
    - { regexp: "# DenyKey=system.run[*]", line: "AllowKey=system.run[*]" }
  tags: zabbix_agent2
#----------------------------------------------------------------------------------------------#
- name: Adcionado Porta firewalld  Zabbix_Agent2 
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10050/tcp
    - 10051/tcp
  tags: zabbix_agent2
# ----------------------------------------------------------------------------------------------#
- name: Iniciar/ Habilitar zabbix-agent2 
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes
  notify: restart linux zabbix-agent
  tags: zabbix_agent2
#-------------------------------------------------------------------------------#
- name: Reload no firewalld 
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  tags: zabbix_agent2
...
