---
# tasks file for install_zabbix_server
# -------------------------------------------------------------------------------------------#
- name: Adcionando Repositorio Zabbix - CentOS8
  dnf:
    name: '{{ url_packages_zabbix }}'
    #name: 'http://repo.zabbix.com/zabbix/5.5/rhel/8/x86_64/zabbix-release-5.5-1.el8.noarch.rpm'
    state: present
  tags: zabbix_server
# --------------------------------------------------------------------------------------------#
#
- name: Instalando pacotes zabbix-server zabbix-agent zabbix-sql-scripts
  dnf:
    name: "{{ packages_zabbix_server}}"
    state: latest
  tags: zabbix_server
  when: ansible_distribution == "CentOS"
# --------------------------------------------------------------------------------------------#
- name: Iniciar/ Habilitar zabbix-server / zabbix-agent2
  systemd:
    name: zabbix-server
    state: started
    enabled: yes
  tags: zabbix_server
  when: ansible_distribution == "CentOS"
#----------------------------------------------------------------------------------------------#
- name: Iniciar/ Habilitar zabbix-server / zabbix-agent2
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes
  tags: zabbix_server
  when: ansible_distribution == "CentOS"

#----------------------------------------------------------------------------------------------#
#
- name: Adcionado Porta firewalld  Zabbix_Server/Zabbix_Agent
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10051/tcp
    - 10050/tcp
    - 3306/tcp
  tags: zabbix_server
  when: ansible_distribution == "CentOS"
# ----------------------------------------------------------------------------------------------#
- name: Reload no firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  tags: zabbix_server
#-------------------------------------------------------------------------------#
- name: SSH | Setando configurações de segurança no arquivo zabbix_server.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_server.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: '# DBHost=localhost', line: 'DBHost={{ zbx_db }}' }
    - { regexp: 'DBName=zabbix', line: 'DBName={{ db_name }}' }
    - { regexp: 'DBUser=zabbix', line: 'DBUser={{ db_user_server }}' }
    - { regexp: '# DBPassword=', line: 'DBPassword={{ db_user_pass_server }}' }
    - { regexp: '# StartPollers=5', line: 'StartPollers=10' }
    - { regexp: '# StartPollers=5', line: 'StartPollers=10' }
    - { regexp: '# StartPingers=1', line: 'StartPingers=5' }
    - { regexp: '# CacheSize=8M', line: 'CacheSize=512M' }
    - { regexp: '# ValueCacheSize=8M', line: 'ValueCacheSize=1024M' }
    - { regexp: '# VMwareCacheSize=8M', line: 'VMwareCacheSize=1024M' }
  when: ansible_distribution == "CentOS"
  tags: zabbix_server
#-----------------------------------------------------------------------------------#
- name: MYCNF | Copiando Arquivo .my.cnf default
  copy: 
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { src: '.my.cnf', dest: '/root/.my.cnf'}
  when: ansible_distribution == "CentOS"
#-----------------------------------------------------------------------------------#
- name: Importando schema da database do zabbix servidor "{{ zbx_db }}"
  #shell: "zcat /usr/share/doc/zabbix-sql-scripts/mysq/create.sql.gz | mysql -h '{{ zbx_db }}' -u '{{ db_user_server }}' -p'{{ db_user_pass_server }}' {{ db_name }}"
  shell: "zcat /usr/share/doc/zabbix-sql-scripts/mysql/create.sql.gz | mysql -h 172.18.10.120 -u zabbix_server -pzabbix zabbix"
  ignore_errors: yes
  when: ansible_distribution == "CentOS"
# --------------------------------------------------------------------------------------------#
- name: Iniciar/ Restart Zabbix-Server/Zabbix-agent2
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - zabbix-server
    - zabbix-agent2
  tags: zabbix_server
  when: ansible_distribution == "CentOS"
#----------------------------------------------------------------------------------------------#

...
