---

- name: Instale todas as atualizações de segurança, críticas e cumulativas .
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: yes

- name: Certifique-se de esperar o tempo suficiente para que as atualizações sejam aplicadas durante a reinicialização.
  win_updates:
      reboot: yes
      reboot_timeout: 300

...
